// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getApiKeyByHash = `-- name: GetApiKeyByHash :one
SELECT
    id,
    tenant_id,
    key_hash,
    name,
    role,
    is_active,
    created_at,
    expires_at
FROM
    api_keys
WHERE
    key_hash = $1
    AND is_active = true
LIMIT 1
`

func (q *Queries) GetApiKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getApiKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.KeyHash,
		&i.Name,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT
    id,
    name,
    plan,
    created_at,
    updated_at
FROM
    tenants
WHERE
    id = $1
LIMIT 1
`

func (q *Queries) GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
