// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID        string           `json:"id"`
	TenantID  uuid.UUID        `json:"tenant_id"`
	KeyHash   string           `json:"key_hash"`
	Name      string           `json:"name"`
	Role      string           `json:"role"`
	IsActive  bool             `json:"is_active"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

type Tenant struct {
	ID        uuid.UUID        `json:"id"`
	Name      string           `json:"name"`
	Plan      string           `json:"plan"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
